/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalAdmin8f2c7eRouteImport } from './routes/portal-admin-8f2c7e'
import { Route as VaultSuper9a3b4dRouteImport } from './routes/vault-super-9a3b4d'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdmin8f2c7eRoute = PortalAdmin8f2c7eRouteImport.update({
  id: '/portal-admin-8f2c7e',
  path: '/portal-admin-8f2c7e',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultSuper9a3b4dRoute = VaultSuper9a3b4dRouteImport.update({
  id: '/vault-super-9a3b4d',
  path: '/vault-super-9a3b4d',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal-admin-8f2c7e': typeof PortalAdmin8f2c7eRoute
  '/vault-super-9a3b4d': typeof VaultSuper9a3b4dRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal-admin-8f2c7e': typeof PortalAdmin8f2c7eRoute
  '/vault-super-9a3b4d': typeof VaultSuper9a3b4dRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal-admin-8f2c7e': typeof PortalAdmin8f2c7eRoute
  '/vault-super-9a3b4d': typeof VaultSuper9a3b4dRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portal-admin-8f2c7e' | '/vault-super-9a3b4d'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portal-admin-8f2c7e' | '/vault-super-9a3b4d'
  id: '__root__' | '/' | '/portal-admin-8f2c7e' | '/vault-super-9a3b4d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalAdmin8f2c7eRoute: typeof PortalAdmin8f2c7eRoute
  VaultSuper9a3b4dRoute: typeof VaultSuper9a3b4dRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-admin-8f2c7e': {
      id: '/portal-admin-8f2c7e'
      path: '/portal-admin-8f2c7e'
      fullPath: '/portal-admin-8f2c7e'
      preLoaderRoute: typeof PortalAdmin8f2c7eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault-super-9a3b4d': {
      id: '/vault-super-9a3b4d'
      path: '/vault-super-9a3b4d'
      fullPath: '/vault-super-9a3b4d'
      preLoaderRoute: typeof VaultSuper9a3b4dRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalAdmin8f2c7eRoute: PortalAdmin8f2c7eRoute,
  VaultSuper9a3b4dRoute: VaultSuper9a3b4dRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
